temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.b[1]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.b1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.b[2]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.b2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.b[3]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.b3.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.b[4]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.b4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.b[5]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.b5.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.b[1]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.b1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.b[2]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.b2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.b[3]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.b3.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.b[4]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.b4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.b[5]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.b5.png")
dev.off()

#temp<-which((rownames(jagsfit.mcmc$summary)=="bSat[1]")==T)
#plot(jagsfit.mcmc$sims.array[,1,temp])
#points(jagsfit.mcmc$sims.array[,2,temp],col=2)
#points(jagsfit.mcmc$sims.array[,3,temp],col=3)

#temp<-which((rownames(jagsfit.mcmc$summary)=="bSat[2]")==T)
#plot(jagsfit.mcmc$sims.array[,1,temp])
#points(jagsfit.mcmc$sims.array[,2,temp],col=2)
#points(jagsfit.mcmc$sims.array[,3,temp],col=3)

#temp<-which((rownames(jagsfit.mcmc$summary)=="bSat[3]")==T)
#plot(jagsfit.mcmc$sims.array[,1,temp])
#points(jagsfit.mcmc$sims.array[,2,temp],col=2)
#points(jagsfit.mcmc$sims.array[,3,temp],col=3)

#temp<-which((rownames(jagsfit.mcmc$summary)=="bSat[4]")==T)
#plot(jagsfit.mcmc$sims.array[,1,temp])
#points(jagsfit.mcmc$sims.array[,2,temp],col=2)
#points(jagsfit.mcmc$sims.array[,3,temp],col=3)


temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.r[1]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.r1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.r[2]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.r2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.r[3]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.r3.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.r[4]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.r4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="alpha0.r[5]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//alpha0.r5.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.r[1]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.r1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.r[2]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.r2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.r[3]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.r3.png")
dev.off()


temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.r[4]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.r4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="beta0.r[5]")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//beta0.r5.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="phi.juv")==T)
plot(jagsfit.mcmc$sims.array[,1,temp],ylim=c(0,2))
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//sigma.year.juv.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="phi.ad")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//sigma.year.ad.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="phi.b")==T)
plot(jagsfit.mcmc$sims.array[,1,temp],ylim=c(0,0.4))
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//sigma.year.b.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="phi.r")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//sigma.year.r.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.ad.intercept.region1")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.ad.intercept.region1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.ad.intercept.region2")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.ad.intercept.region2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.ad.intercept.region3")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.ad.intercept.region3.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.ad.intercept.region4")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.ad.intercept.region4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.ad.intercept.region5")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.ad.intercept.region5.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.juv.intercept.region1")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.juv.intercept.region1.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.juv.intercept.region2")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.juv.intercept.region2.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.juv.intercept.region3")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.juv.intercept.region3.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.juv.intercept.region4")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.juv.intercept.region4.png")
dev.off()

temp<-which((rownames(jagsfit.mcmc$summary)=="omega.juv.intercept.region5")==T)
plot(jagsfit.mcmc$sims.array[,1,temp])
points(jagsfit.mcmc$sims.array[,2,temp],col=2)
points(jagsfit.mcmc$sims.array[,3,temp],col=3)
dev.copy(png,"Results//LongRun3August//Convergence check//omega.juv.intercept.region5.png")
dev.off()